/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.table.*;
import dao.AlunoDAO;
import core.Aluno;
import java.util.List;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author aalbano
 */
public class AlunosUI extends javax.swing.JFrame {

        /**
         * Creates new form Dashboard
         */
        public AlunosUI() {
                initComponents();
                setLocationRelativeTo(null);
                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                carregarDados();
                
                pesquisarDados();
             
                editarDados();
        }
        
        private void pesquisarDados() {
            DefaultTableModel mdl = (DefaultTableModel) tblAlunos.getModel();

            TableRowSorter<DefaultTableModel> srt = new TableRowSorter<>(mdl);

            tblAlunos.setRowSorter(srt);

            txtPesquisar.getDocument().addDocumentListener(new DocumentListener() {

                private void pesquisar() {
                    String txt = txtPesquisar.getText();

                    if (txt.trim().isEmpty()) {
                        srt.setRowFilter(null);
                    } else {
                        srt.setRowFilter(RowFilter.regexFilter("(?i)" + txt));
                    }
                }

                @Override
                public void insertUpdate(DocumentEvent e) {
                    pesquisar();
                }

                @Override
                public void removeUpdate(DocumentEvent e) {
                    pesquisar();
                }

                @Override
                public void changedUpdate(DocumentEvent e) {
                    pesquisar();
                }
            });
        }
        
        private void editarDados() {
            DefaultTableModel mdl =
                (DefaultTableModel) tblAlunos.getModel();

            mdl.addTableModelListener(e -> {

                if (e.getType() != javax.swing.event.TableModelEvent.UPDATE) {
                    return;
                }

                int row = e.getFirstRow();

                try {

                    int id = (int) mdl.getValueAt(row, 0);

                    Aluno al = AlunoDAO.buscarPorId(id);

                    al.setNome(
                        mdl.getValueAt(row, 1).toString()
                    );

                    al.setCpf(
                        mdl.getValueAt(row, 4).toString()
                    );

                    al.setTel(
                        mdl.getValueAt(row, 5).toString()
                    );

                    AlunoDAO.atualizar(al);

                } catch (Exception ex) {

                    System.err.println(
                        "Erro ao atualizar aluno: " +
                        ex.getMessage()
                    );
                }
            });
        }

        /**
         * Carrega os dados de alunos do banco de dados
         */
        public void carregarDados() {
                DefaultTableModel mdl = (DefaultTableModel) tblAlunos.getModel();
                mdl.setRowCount(0); // Limpa a tabela

                try {
                        List<Aluno> alunos = AlunoDAO.listarTodos();
                        for (Aluno a : alunos) {
                                mdl.addRow(
                                new Object[] { 
                                    a.getId(), 
                                    a.getNome(),
                                    a.getEmail(),
                                    a.getDtNascFormatada(),
                                    a.getCpf(),
                                    a.getTel(),
                                });
                        }
                } catch (Exception e) {
                        System.err.println("Erro ao carregar alunos: " + e.getMessage());
                }
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAlunos = new javax.swing.JTable();
        txtPesquisar = new javax.swing.JTextField();
        btnAdicionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setText("EduManager");

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel7.setText("Alunos");

        tblAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matrícula", "Nome", "Email", "Data de Nascimento", "CPF", "Telefone"
            }
        ));
        tblAlunos.setShowGrid(true);
        jScrollPane2.setViewportView(tblAlunos);

        txtPesquisar.setToolTipText("");
        txtPesquisar.setName(""); // NOI18N
        txtPesquisar.addActionListener(this::txtPesquisarActionPerformed);

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(this::btnAdicionarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(316, 316, 316))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicionar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarActionPerformed


    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {
            CadastroAluno ca = new CadastroAluno(this);
            ca.setVisible(true);

            carregarDados();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblAlunos;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
